### ISSUE TITLE
Упорядочить структуру документа.

### ISSUE THREAD

**Issue by genuisereal** [stubborn153/Bussiness-Process-1#5]
Понятно, что мы пока учимся создавать документ о бзинес процессе, и пока неясно на данном этапе, что и как должно быть описано и организовано.
Но некоторые мысли есть уже сейчас. Эти идеи основаны на предыдущем опыте. 
И их полезно использовать.

Стурктура: документ о бизнеспроцессе рассчитан на перспективу внедрения в реальную должностную инструкцию и что важнее в реальную практику работы менеджера.
А значит конечной целью подготовки такого документа должен стать некий формуляр (на бумажном или цифровом носителе (ексель файл, текстовый файл, или же issue в github)). 
В самом простом случае можно представить чек лист с пунктами, с кратким описанием действий и чекбоксами, которые проставляются ручкой.
Менеджер в процессе каждодневных обязанностей, перед началом каждого нового "бизнес процесса" - т.е. переговоров с заказчиком по новому заказу, должен подготовить чистый бланк для него.
И вести переговоры постоянно отмечая в бланке на каком шаге он находится, и по каким вопросам уже достигнута договоренность, а по каким еще нет. 
Такой подход в иедале дает возможность всегда иметь перед глазами во время разговора, всю историю переговоров и уже принятые решения. 
Позволяет не хранить всю эту информацию в памяти. 
И позволяет упорядочить процесс переговорв по каждому заказу в отдельности, что сделано, что нет, и на какой стадии находятся переговры.

Таким образом, подготовка схемы алгоритма, описание сокращений и конкретных исторических данных, локализация допущенных ошибок приведших к упущенной выгоде, и оценочные суммы упущенныех выгод, являются невидимой подготовительной работой (подводной частью айсберга) верхушкой которой должен стать конкретный формуляр, чек лист, бланк заказа, который будет являтся непосредственным инструментом для работы мендеждера.

После того как превый цикл описания алгоритма, анализа ошибок и оценка упущенных выгод произведены и сформирован актуальный формуляр, его внедряют в каждодневную практику.

В процессе работы возникают старые и новые ошибки, улучшения или ухудшения, которые снова приводят к переосмыслению алгоритма и дополнению описания ошибок и упущеных выгод, или наоборот улучшений. И их снова вносят в документ и обновляют формуляр.

И этот процесс продолжается до тех пор пока не удаётся достигнуть заметного улучшения в показателях работы менеджера по этому конкретному бизнес процессу.

Таким образом в документе должны быть обязвтельно следующие пункты:
1) схема алгоритма
2) описание исторических случаев об ошибках
3) статики оценок упущенных выгод
4) актуальный формуляр, который предположительно позволит предотвратить все описанные ошибки.

**Comment by stubborn153** [comment]
Структура документа упорядочена. Разработан формуляр работы с претензиями. Разработан формуляр приема заказа мозаики. 06.02.2017
